name: navigation
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  geolocator: ^10.1.0
  sensors_plus: ^4.0.2
  latlong2: ^0.9.0
  url_launcher: ^6.2.3
  rxdart: ^0.27.7
  geocoding: ^2.1.1
  flutter_compass: ^0.8.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.6
  json_annotation: ^4.8.1
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:

  uses-material-design: true
